import { Router, type IRouter } from "express";
import healthRouter from "./health.routes";
import authRouter from "../modules/auth/auth.routes";
import userRouter from "../modules/users/user.routes";
import vendorRouter from "../modules/vendors/vendor.routes";
import serviceRouter from "../modules/services/service.routes";
import productRouter from "../modules/products/product.routes";
import portfolioRouter from "../modules/portfolio/portfolio.routes";
import categoryRouter from "../modules/categories/category.routes";
import bookingRouter from "../modules/bookings/booking.routes";
import reviewRouter from "../modules/reviews/review.routes";
import savedRouter from "../modules/saved/saved.routes";
import followRouter from "../modules/follows/follow.routes";
import searchRouter from "../modules/search/search.routes";
import recommendationRouter from "../modules/recommendations/recommendation.routes";
import conversationRouter from "../modules/conversations/conversation.routes";
import adminRouter from "../modules/admin/admin.routes";
import settingsRouter from "../modules/settings/settings.routes";
import complianceRouter from "../modules/compliance/compliance.routes";
import analyticsRouter from "../modules/analytics/analytics.routes";
import uploadsRouter from "../modules/uploads/uploads.routes";
import paymentsRouter from "../modules/payments/payments.routes";
import notificationsRouter from "../modules/notifications/notifications.routes";
import announcementsRouter from "../modules/announcements/announcement.routes";
import newsletterRouter from "../modules/newsletter/newsletter.routes";

const v1Router: IRouter = Router();
v1Router.use("/auth", authRouter);
v1Router.use("/users", userRouter);
v1Router.use("/vendors", vendorRouter);
v1Router.use("/categories", categoryRouter);
v1Router.use("/bookings", bookingRouter);
v1Router.use("/conversations", conversationRouter);
v1Router.use("/admin", adminRouter);
v1Router.use("/settings", settingsRouter);
v1Router.use("/compliance", complianceRouter);
v1Router.use("/analytics", analyticsRouter);
v1Router.use("/", reviewRouter);
v1Router.use("/", savedRouter);
v1Router.use("/", followRouter);
v1Router.use("/", searchRouter);
v1Router.use("/", recommendationRouter);
v1Router.use("/", serviceRouter);
v1Router.use("/", productRouter);
v1Router.use("/uploads", uploadsRouter);
v1Router.use("/payments", paymentsRouter);
v1Router.use("/notifications", notificationsRouter);
v1Router.use("/announcements", announcementsRouter);
v1Router.use("/newsletter", newsletterRouter);
v1Router.use("/", portfolioRouter);

const router: IRouter = Router();
router.use("/api", healthRouter);
router.use("/api/v1", v1Router);

export default router;
